export const albumData = [
  {
    id: 14,
    src: "/images/albumArt/smear.png",
    alt: "a picture of the smear album cover",
    artist: "Zach Brose",
    album: "Smear",
    year: 2022,
    link: "https://zachbrose.bandcamp.com/album/smear",
    role: "all instruments, producer, mixer, engineer",
    blog: "Smear is Zach's first full-length instrumental album",
  },
  {
    id: 13,
    src: "/images/albumArt/mik.webp",
    artist: "Mik Cool",
    album: "I Wanna Be Cool",
    year: 2022,
    link: "https://www.mikcoolmusic.com/",
    role: "producer, mixing, guitars, synth, bass",
  },
  {
    id: 12,
    src: "/images/albumArt/marathoner.jpg",
    artist: "Marathoner",
    album: "Marathoner (EP)",
    year: 2022,
    link: "https://marathoner.bandcamp.com/album/marathoner",
    role: "producer, guitar",
  },
  {
    id: 11,
    src: "/images/albumArt/itsYourWorld.jpg",
    alt: "a picture of the its your world album cover",
    artist: "Zach Brose",
    album: "It's Your World",
    year: 2021,
    link: "https://zachbrose.bandcamp.com/album/its-your-world",
    role: "all instruments, producer, mixer, engineer",
    blog: "This record is tight",
  },
  {
    id: 10,
    src: "/images/albumArt/dayTapes2.jpg",
    alt: "a picture of the day tapes 2 cover",
    artist: "Zach Brose",
    album: "Day Tapes, Vol. 2",
    year: 2021,
    link: "https://zachbrose.bandcamp.com/album/day-tapes-vol-2",
    role: "all instruments, producer, mixer, engineer",
    blog: "This record is tight",
  },
  {
    id: 9,
    src: "/images/albumArt/dayTapes1.jpg",
    alt: "a picture of the day tapes 1 cover",
    artist: "Zach Brose",
    album: "Day Tapes, Vol. 1",
    year: 2021,
    link: "https://zachbrose.bandcamp.com/album/day-tapes-vol-1",
    role: "all instruments, producer, mixer, engineer",
    blog: "This record is tight",
  },
  {
    id: 8,
    src: "/images/albumArt/kansasPlates3.jpg",
    alt: "a picture of the kansas plates album cover",
    artist: "Kansas Plates",
    album: "Kansas Plates",
    year: 2021,
    link: "https://kansasplates.bandcamp.com/album/kansas-plates",
    role: "guitar, writer",
    blog: "This record is tight",
  },
  {
    id: 7,
    src: "/images/albumArt/youarehere.jpg",
    artist: "Jessica Manning",
    album: "You Are Here",
    year: 2021,
    role: "producer (except Know Better), writer, guitars, synth",
    link: "https://jessicamanning.bandcamp.com/album/what-if-i-run",
  },
  {
    id: 6,
    src: "/images/albumArt/forYou.jpg",
    alt: "a picture of the for you album cover",
    artist: "Zach Brose and Luke Enyeart",
    album: "For You",
    year: 2021,
    link: "https://zachbrose.bandcamp.com/track/for-you-single",
    role: "guitar, bass, synth, vocals, writer",
    blog: "This record is tight",
  },
  {
    id: 5,
    src: "/images/albumArt/ac3.jpg",
    artist: "Andy Cook",
    album: "I'll Be Fine",
    year: 2020,
    role: "guitar",
    link: "https://andycookandy.bandcamp.com/album/ill-be-fine",
  },
  {
    id: 4,
    src: "/images/albumArt/kansasplates1.jpg",
    alt: "a picture of the kansas plates album cover",
    artist: "Kansas Plates",
    album: "Operator",
    year: 2019,
    link: "https://kansasplates.bandcamp.com/album/operator-2",
    role: "guitar, writer",
    blog: "This record is tight",
  },
  {
    id: 3,
    src: "/images/albumArt/arBirn.jpg",
    alt: "a picture of the ar.birn album cover",
    artist: "Ar.Birn",
    album: "ar.birn",
    year: 2018,
    link: "https://arbirn.bandcamp.com/album/ar-birn",
    role: "guitar, vocals, writer",
    blog: "This record is tight",
  },
  {
    id: 2,
    src: "/images/albumArt/andycook1.jpg",
    artist: "Andy Cook",
    album: "Modern Man",
    year: 2018,
    role: "guitar",
    link: "https://andycookandy.bandcamp.com/album/modern-man",
  },
  {
    id: 1,
    src: "/images/albumArt/whatifirun.jpg",
    artist: "Jessica Manning",
    album: "What If I Run",
    year: 2017,
    role: "writer, guitars, synth",
    link: "https://jessicamanning.bandcamp.com/album/you-are-here",
  },
];
